ergebnis/.github

.github/settings.yml
=> Enhancement: Configure repository topics

.github/settings.yml
=> Fix: Add missing period

FUNDING.yml
This PR
💁‍♂ For reference, see https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository.
=> Fix: Custom links

CODEOWNERS
=> Enhancement: Add @ergebnis-bot to CODEOWNERS

FUNDING.yml
=> Fix: Use https

FUNDING.yml
=> Enhancement: Add Amazon wishlist

FUNDING.yml
=> Enhancement: Add Cottonbureau

FUNDING.yml
=> Enhancement: Add link to ko-fi.com

FUNDING.yml
=> Fix: Remove link to amazon.com

FUNDING.yml
=> Fix: Use shorter link for buymeacoffee.com

.github/CONTRIBUTING.md, .github/workflows/triage.yaml
=> Enhancement: Add triage workflow

FUNDING.yml
=> Fix: Use amazon.com instead of paypal.com

PULL_REQUEST_TEMPLATE.md
This PR
💁‍♂️ For reference, see https://github.blog/changelog/2020-12-15-markdown-list-syntax-now-autocompleted/.
=> Fix: Remove check box

.github/workflows/release.yaml, README.md
=> Enhancement: Add release workflow

actions/composer/determine-cache-directory/action.yaml, actions/composer/install/action.yaml, actions/composer/install/run.sh
=> Enhancement: Share composer actions

actions/composer/install/run.sh
=> Fix: Indentation

CHANGELOG.md, actions/composer/determine-cache-directory/action.yaml
=> Enhancement: Add `working-directory` input for `composer/determine-cache-directory` action

.github/workflows/release.yaml
=> Enhancement: Use `actions/github-script` to create release with release body

.github/workflows/triage.yaml
=> Fix: Return early

.github/workflows/triage.yaml
This pull request
💁‍♂️ Unsure why Dependabot does not update it.
=> Fix: Update `actions/github-script`

.github/workflows/merge.yaml, CHANGELOG.md, actions/github/add-assignee-to-pull-request/action.yaml
=> Enhancement: Add `github/add-assignee-to-pull-request action`

actions/github/add-assignee-to-pull-request/action.yaml
This pull request
💁‍♂️ For reference, see https://github.com/actions/toolkit/tree/main/packages/core#inputsoutputs.
=> Enhancement: Use `core` to obtain input

.github/workflows/merge.yaml, CHANGELOG.md, actions/github/merge-pull-request/action.yaml
=> Enhancement: Add `github/merge-pull-request` action

actions/github/pull-request/approve/action.yaml, actions/github/pull-request/merge/action.yaml
=> Fix: Add semicolon

.github/workflows/triage.yaml, CHANGELOG.md, actions/github/pull-request/add-label-based-on-branch-name/action.yaml
=> Enhancement: Add `github/pull-request/add-label-based-on-branch-name` action

actions/github/pull-request/add-assignee/action.yaml, actions/github/pull-request/add-label-based-on-branch-name/action.yaml, actions/github/pull-request/approve/action.yaml, actions/github/pull-request/merge/action.yaml
=> Fix: Conditions

.github/workflows/triage.yaml
=> Fix: Checkout

.github/workflows/merge.yaml, .github/workflows/triage.yaml
=> Fix: References

.github/workflows/release.yaml, CHANGELOG.md, actions/github/release/create/action.yaml
=> Enhancement: Add `github/release/create` action

.github/workflows/merge.yaml, CHANGELOG.md, actions/github/pull-request/request-review/action.yaml
=> Enhancement: Add `github/pull-request/request-review` action

.github/workflows/merge.yaml, .github/workflows/release.yaml, .github/workflows/triage.yaml
=> Fix: Use tag as reference

CHANGELOG.md, actions/github/pull-request/request-review/action.yaml
=> Fix: Condition

CHANGELOG.md, actions/github/pull-request/add-assignee/action.yaml, actions/github/pull-request/add-label-based-on-branch-name/action.yaml, actions/github/pull-request/approve/action.yaml, actions/github/pull-request/merge/action.yaml, actions/github/pull-request/request-review/action.yaml, actions/github/release/create/action.yaml
=> Enhancement: Update `actions/github-script`

CHANGELOG.md, actions/github/release/create/action.yaml
=> Enhancement: Expose `RELEASE_ID` and `RELEASE_UPLOAD_URL` environment variables

.github/dependabot.yml
This pull request
💁‍♂️ For reference, see https://github.com/dependabot/dependabot-core/issues/4178#issuecomment-1118492006.
=> Enhancement: Let dependabot update dependencies in composite actions

README.md
=> Fix: Document composite actions

CHANGELOG.md, README.md, actions/oh-dear/maintenance-period/start/action.yaml, actions/oh-dear/maintenance-period/stop/action.yaml
=> Enhancement: Add composite actions for starting and stopping maintenance periods on Oh Dear

CHANGELOG.md, README.md, actions/oh-dear/check/request-run/action.yaml
=> Enhancement: Add composite action for requesting a check run on Oh Dear

.github/dependabot.yml, CHANGELOG.md, README.md, actions/phive/install/action.yaml
=> Enhancement: Add composite action for installing dependencies with `phive`
