ergebnis/.github

- CODEOWNERS
This PR
💁‍♂ This is a temporary work-around until https://github.com/dependabot/feedback/issues/86#issuecomment-568274751 is resolved.
> Fix: Remove CODEOWNERS

- CODEOWNERS
> Fix: Restore CODEOWNERS

- CODEOWNERS
This PR
Follows https://github.com/ergebnis/php-library-template/pull/363.
> Fix: Remove @ergebnis-bot from CODEOWNERS

- CODEOWNERS
> Fix: Add @ergebnis-bot to CODEOWNERS

- CODEOWNERS
> Fix: CODEOWNERS

- .github/settings.yml
- README.md
This PR
💁‍♂️ For reference, see https://twitter.com/github/status/1278433248994091022.
> Fix: Update links to GitHub documentation

- .editorconfig
- .github/CONTRIBUTING.md
- .github/dependabot.yml
- .github/settings.yml
- .github/workflows/integrate.yaml
- .yamllint.yaml
- FUNDING.yml
- Makefile
- README.md
> Enhancement: Add integrate workflow

- CODEOWNERS
> Fix: Code owners

- FUNDING.yml
> Fix: Link to shop.localheinz.com instead of cottonbureau.com

- PULL_REQUEST_TEMPLATE.md
> Fix: Avoid acronym

- README.md
> Fix: Add missing badge

- .github/workflows/triage.yaml
> Fix: Run workflow on `pull_request_target`

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
> Fix: Use dashes instead of asterisks for unordered lists

- CHANGELOG.md
- actions/composer/install/action.yaml
- actions/composer/install/run.sh
> Enhancement: Add `working-directory` input for `composer/install` action

- CHANGELOG.md
- actions/composer/install/run.sh
> Fix: Add missing dash

- .github/workflows/merge.yaml
- .github/workflows/release.yaml
- .github/workflows/triage.yaml
> Fix: Use semicolon and trailing commas

- .github/workflows/merge.yaml
- CHANGELOG.md
- actions/github/approve-pull-request/action.yaml
> Enhancement: Add `github/approve-pull-request` action

- .github/workflows/triage.yaml
> Fix: Adjust usage of `octokit`

- actions/github/add-assignee-to-pull-request/action.yaml
This pull request
💁‍♂️ For reference, see https://github.com/actions/github-script#use-env-as-input.
> Fix: Use environment variable to pass input to script

- CHANGELOG.md
- actions/github/release/create/action.yaml
> Enhancement: Expose `RELEASE_HTML_URL` environment variable

- .editorconfig
- README.md
> Fix: Document all side effects

- .editorconfig
- .github/CODEOWNERS
- .github/CONTRIBUTING.md
- .github/SECURITY.md
- .github/dependabot.yaml
- .github/settings.yml
- .github/workflows/integrate.yaml
- .github/workflows/merge.yaml
- .github/workflows/release.yaml
- .github/workflows/triage.yaml
- .yamllint.yaml
- LICENSE.md
- README.md
> Enhancement: Synchronize with `ergebnis/php-package-template`

- actions/phive/install/action.yaml
I've noticed a bug in the Phive install action where the cache key is incorrectly calculated. Instead of generating a hash from `phars.xml`, the function name is printed as a string, leading to cache failures when `phars.xml` is updated in a single pull request.
**Current Output:**
**Fix:**
I updated the cache key calculation from:
```
key: "phive-hashFiles('**/phars.xml')"
```
to:
```
key: phive-${{ hashFiles('**/phars.xml') }}
```
**After fix is applied:**
This should ensure the correct hash is generated and the cache is restored properly.
I encountered a similar issue in my [wayofdev/gh-actions](https://github.com/wayofdev/gh-actions) repository, which also uses Phive install inspired by your repository.
https://github.com/cli/cli can be used to check all cache keys of repository:
``` …
```
> Fix Cache Key Calculation in Phive Install GitHub Action

- actions/github/pull-request/add-label-based-on-branch-name/action.yaml
> fix(actions) - expose correct variable name for branch name

- CHANGELOG.md
- README.md
- actions/github/release/publish/action.yaml
> Enhancement: Add `github/actions/publish` to allow publishing a release
